title: The-Least-Eligible-Codes
description: "최대의 자유가 최대의 행복이라고 믿는 자유주의 개발자"
author:
  name: "Nick the cat"
  email: "dohp.kim@gmail.com"
  url: "https://github.com/s1000f"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

# Custom variables
owner : "Nick the cat"
year : "2022"
